name: "helitech"
version: 1.0
environment: "local"
app:
  port: 7003
database:
  host: "ht-postgres"
  port: 5445
  username: "postgres"
  password: "secret"
  db_name: "postgres"
logger:
  level: "debug"
sqs:
  region: "us-east-1"
  accessKeyId: "access-key"
  secretAccessKey: "secret-key"
  queueName: "ht-queue"
  deadLetterQueueName: "dlq"
  visibilityTimeout: 30
  maxRetries: 3
  waitTime: 20
  maxMessages: 10
  endpoint: "http://localhost:4566"
