name: "helitech"
version: 1.0
environment: "docker"
app:
  port: 8080
database:
  host: "ht-postgres"
  port: 5432
  username: "user"
  password: "secret"
  db_name: "postgres"
logger:
  level: "debug"
sqs:
  region: "us-east-1"
  accessKeyId: "access-test"
  secretAccessKey: "secret-test"
  queueName: "ht-queue"
  deadLetterQueueName: "dlq"
  visibilityTimeout: 30
  maxRetries: 3
  waitTime: 20
  maxMessages: 10
  endpoint: "http://ht-localstack:4566"
